### ISSUE TITLE
Does this work with ZF3?

### ISSUE THREAD

**Issue by ghost** [mikemix/dompdfmodule#2]
Hello
I was trying to implement this for zf3 but i get an exception. I would be really great if you could inform if its fully compatible with zf3 or not. With Zf2 it works really well. 

Thanks in advance .

**Comment by mikemix** [comment]
For now this module is not compatible with ZF3. I'll make it compatible though, but not until tomorrow.

**Comment by ghost** [comment]
Awesome!!!!Thank you very much i would really be grateful to you if this can be done by tomorrow.

**Comment by mikemix** [comment]
Version 3.0 is now compatible with ZF3.
