### ISSUE TITLE
Idea to add module to controller factory

### ISSUE THREAD

**Issue by yuristru** [mikemix/dompdfmodule#4]
Hi,

im not able to insert your module to a zf3 controller factory:

```
use mikemix\dompdfmodule;
class OnboardingControllerFactory implements FactoryInterface
{
public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
    {
        return new OnboardingController(
            $container->get(dompdf::class)
        );
    }
```

What can i use to replace the depricated ServiceManger from your tutorial?

$container->get(dompdf::class) ??
$container->get('dompdf') ??

Glad to hear from you :-)
best regards, Yuri

**Comment by mikemix** [comment]
Sorry for late answer :( hopefully this will reach someone else needing help with this, the service name is literally `dompdf`, not the actual class name.
